services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: perfume-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.4
    container_name: perfume-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./backend/backup/perfume_db:/backup/perfume_db
      - ./backend/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    env_file:
      - ./backend/.env

volumes:
  mongo-data:
